[package]
name = "caf"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
async-trait = "0.1"
futures = "0.3"
libp2p = { version = "0.54", features = ["dns", "identify", "kad", "macros", "noise", "ping", "request-response", "tcp", "tokio", "yamux"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
unsigned-varint = { version = "0.7", features = ["futures"] }
clap = { version = "4", features = ["derive"] }
